social_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('twitter.urls')),
                  path('accounts/', include('allauth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#intenta poner una imagen si no hay una por defctoen los perfiles

twitter/urls.py
from django.urls import path

from twitter.views import home, DeletePost, profile, edit_profile

app_name = 'twitter'

urlpatterns = [
    path('', home, name='home'),
    path('deletepost/<int:pk>/', DeletePost.as_view(), name='delete-post'),
    path('profile/<str:username>/', profile, name='profile'),
    path('edit_profile/', edit_profile, name='edit-profile'),
]

twitter/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(default='hola, twitter', max_length=200)
    image = models.ImageField(default='images.png')

    # images

    def __str__(self):
        return f'Perfil de {self.user.username}'


class Post(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.content

twitter/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row
from django import forms
from django.contrib.auth.models import User

from twitter.models import Post, Profile


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'content',
        ]

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.helper = FormHelper()
            self.fields['content'].label = 'insgrese contenido aqui'
            self.fields['content'].widget.attrs['placeholder'] = 'ingrese un texto'
            self.helper.layout = Layout(
                Row(
                    Column('content', css_class='col-md-12'),
                    css_class='form-row'
                ),
            )


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'username']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'bio']

twitter/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView

from twitter.forms import PostForm, UserUpdateForm, ProfileUpdateForm
from twitter.models import Post


@login_required
def home(request):
    posts = Post.objects.all()
    if request.method == 'POST':
        if request.user.is_authenticated:
            form = PostForm(request.POST)

            if form.is_valid():
                create_post = Post.objects.create(
                    content=form.cleaned_data.get('content'),
                    user=request.user
                )
                create_post.save()
                return redirect('twitter:home')

    else:
        form = PostForm()

    context = {'posts': posts, 'form': form}
    return render(request, 'twitter/newsfeed.html', context)


class PostView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'social/post.html'
    success_url = reverse_lazy('twitter:home')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class DeletePost(DeleteView):
    model = Post
    success_url = reverse_lazy('twitter:home')


def profile(request, username):
    user = User.objects.get(username=username)
    posts = user.posts.all()
    context = {'user': user, 'posts': posts}
    return render(request, 'twitter/profile.html', context)


def edit_profile(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('twitter:home')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm()
    context = {'user_form': user_form, 'profile_form': profile_form}
    return render(request, 'twitter/editar.html', context)

templates/twitter/editar.html
{% extends 'twitter/layout.html' %}

{% block content %}

    <div id="main" class="container-fluid d-flex">
        <div class="">
            <div id="inputTweetArea" class="tweet-wrap2">
                <div class="d-flex">
                    <div class="col-xs">
                        <!-- Image form -->
                        <img src="{{ request.user.profile.image.url }}" alt="" class="avator">
                        <!-- Formulario -->
                    </div>

                    <!-- Formulario -->
                    <form class="col pr-0" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="input-wrapper">
                            <label>Nombre</label>
                            {{ user_form.first_name }}
                        </div>
                        <div class="input-wrapper">
                            <label for="user-name-id">Username</label>
                            {{ user_form.username }}
                        </div>
                        <div class="input-wrapper">
                            <label>Bio</label>
                            {{ profile_form.bio }}
                        </div>
                        <div class="input-wrapper">
                            {{ profile_form.image }}
                        </div>

                        <button type="submit" class="twitter-btn">Actualizar</button>
                    </form>
                    <!-- Formulario -->

                </div>
            </div>
        </div>
        <!-- End Center -->
    </div>

{% endblock content %}

templates/twitter/newsfeed.html
{% extends 'twitter/layout.html' %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div id="main" class="container-fluid d-flex">
        <!-- Barra Izquierda -->
        <div class="sidebar m-5 d-none d-md-block">
            <div class="">
                <div class="card " style="width: 18rem; text-align:center;border-radius: 20px;">
                    {% if request.user.profile.image.url %}
                        <img class="card-img-top rounded-circle"
                             style="width:60%; position: relative;left: 62px;padding-top: 20px;"
                             src="{{ request.user.profile.image.url }}"
                             alt="Card image cap">
                    {% else %}
                        <img class="card-img-top rounded-circle"
                             style="width:60%; position: relative;left: 62px;padding-top: 20px;"
                             src="{% static 'img/images.png' %}"
                             alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title font-weight-bold">{{ request.user.first_name }}</h5>
                        <h6 class="card-title font-weight-bold">@{{ request.user.username }}</h6>


                        <p class="card-text">{{ request.user.profile.bio }}</p>
                        <h6 class="card-title font-weight-bold">
                            100 Followers
                            100 Following
                        </h6>
                        <a href="#" class="btn  text-white rounded-pill">Mi perfil</a>
                    </div>

                </div>
                <a href="{% url 'twitter:edit-profile' %}" id="addATweetLeft" onclick="addTweet()" type="button"
                   style="border-radius: 30px; font-size: 1.1rem; font-weight:bold;"
                   class="btn btn-lg btn-block mt-4 text-white ">Editar mi perfil
                </a>
            </div>
        </div>
        <!-- End Barra Izquierda -->

        <!-- Center -->
        <div class="content">

            <div id="inputTweetArea" class="tweet-wrap">
                <div class="d-flex">
                    <div class="col-xs">
                        <!-- Image form -->
                        <img src="{{ request.user.profile.image.url }}" alt=""
                             class="avator">
                        <!-- Formulario -->
                    </div>

                    <!-- Formulario -->
                    <form class="is-form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                            <button type="submit" class="btn btn-primary btn-lg">Twitter</button>
                        </div>
                    </form>
                    <!-- Formulario -->

                </div>
                <div class="d-flex justify-content-center mt-2">
                </div>
            </div>

            <!-- Tweets -->
            {% for post in posts %}
                <div id="tweetCards">
                    <!-- FOR LOOP HERE -->
                    <div class="tweet-wrap" style="border-radius:20px">
                        <div class="tweet-header">
                            <img src="{{ post.user.profile.image.url }}"
                                 alt="" class="avator">
                            <div class="tweet-header-info">
                                {{ post.user.first_name }}<span>@<a
                                    href="{% url 'twitter:profile' post.user.username %}">{{ post.user.username }}</a></span><span>{{ post.created|naturaltime }}
                        </span>
                                <p>{{ post.content }}</p>
                            </div>
                        </div>
                        <div class="tweet-info-counts">

                            <div class="comments">
                                <button style="background: white; border: none;">
                                    <svg class="feather feather-message-circle sc-dnqmqq jxshSx"
                                         xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round" aria-hidden="true">
                                        <path
                                                d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z">
                                        </path>
                                    </svg>
                                </button>
                                <div class="comment-count"></div>
                            </div>

                            <div class="retweets">
                                <button style="background: white; border: none;">
                                    <svg class="feather feather-repeat sc-dnqmqq jxshSx"
                                         xmlns="http://www.w3.org/2000/svg"
                                         width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                         stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                         aria-hidden="true">
                                        <polyline points="17 1 21 5 17 9"></polyline>
                                        <path d="M3 11V9a4 4 0 0 1 4-4h14"></path>
                                        <polyline points="7 23 3 19 7 15"></polyline>
                                        <path d="M21 13v2a4 4 0 0 1-4 4H3"></path>
                                    </svg>
                                </button>
                                <div class="retweet-count"></div>
                            </div>

                            <div class="likes">
                                <button style="background: white; border: none;">
                                    <svg class="feather feather-heart sc-dnqmqq jxshSx"
                                         xmlns="http://www.w3.org/2000/svg"
                                         width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                         stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                         aria-hidden="true">
                                        <path
                                                d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z">
                                        </path>
                                    </svg>
                                </button>
                                <div class="likes-count"></div>
                            </div>

                            <!-- DELETE -->
                            {% if request.user.id == post.user.id %}
                                <div class="trash">
                                    <a href="{% url 'twitter:delete-post' pk=post.id %}"
                                       style="background: white; border: none;">
                                        <i class="fa fa-trash-o" style="color:#657786; font-size: 20px"
                                           aria-hidden="true"></i>
                                    </a>
                                </div>
                            {% endif %}
                            <!-- END-DELETE -->
                        </div>
                    </div>
                    <!-- FOR LOOP HERE -->

                </div>
                <!-- EndTweets -->


                </div>
            {% endfor %}
        <!-- End Center -->


        <!-- Barra Derecha -->
        <div class="sidebar m-5 d-none d-xl-block">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    Who to Follow
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><a href="https://twitter.com/playboicarti"
                                                   style="text-decoration: none;color: #657787;">@playboicarti</a></li>
                    <li class="list-group-item"><a href="https://twitter.com/LILUZIVERT"
                                                   style="text-decoration: none;color: #657787;">@LILUZIVERT</a></li>
                    <li class="list-group-item"><a href="https://twitter.com/NARUTO_kousiki"
                                                   style="text-decoration: none;color: #657787;">@NARUTO_kousiki</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

templates/twitter/post_confirm_delete.html
{% extends 'twitter/layout.html' %}
{% block content %}
    <form class="is-form" method="POST">
        {% csrf_token %}
        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
            <p>estas seguro que desesa eliminar el twitter <h5 class="text-danger">{{ object }}</h5></p>
            <button type="submit" class="btn btn-danger">eliminar</button>
        </div>
    </form>
{% endblock content %}

templates/twitter/profile.html
{% extends 'twitter/layout.html' %}
{% load static %}
{% load humanize %}
{% block content %}
    <div id="main" class="container-fluid d-flex">
        <!-- Barra Izquierda -->
        <div class="sidebar m-5 d-none d-md-block">
            <div class="">
                <div class="card " style="width: 18rem; text-align:center;border-radius: 20px;">
                    <img class="card-img-top rounded-circle"
                         style="width:60%; position: relative;left: 62px;padding-top: 20px;"
                         src="{{ user.profile.image.url }}"
                         alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title font-weight-bold">{{ user.first_name }}</h5>
                        <h6 class="card-title font-weight-bold">@{{ user.username }}</h6>


                        <p class="card-text">{{ user.profile.bio }}</p>
                        <h6 class="card-title font-weight-bold">
                            100 Followers
                            100 Following
                        </h6>
                    </div>

                </div>
                <a href="#" id="addATweetLeft" type="button"
                   style="border-radius: 30px; font-size: 1.1rem; font-weight:bold;"
                   class="btn btn-lg btn-block mt-4 text-white ">Editar mi perfil</a>
            </div>
        </div>
        <!-- End Barra Izquierda -->

        <!-- Center -->
        <div class="content">


            <!-- Tweets -->
            {% for post in posts %}
                <div id="tweetCards">
                    <!-- FOR LOOP HERE -->
                    <div class="tweet-wrap" style="border-radius:20px">
                        <div class="tweet-header">
                            <img src="{{ post.user.profile.image.url }}" alt="" class="avator">
                            <div class="tweet-header-info">
                                {{ post.user.first_name }}
                                <span>@{{ post.user.username }}</span><span>{{ post.created|naturaltime }}
                        </span>
                                <p>{{ post.content }}</p>
                            </div>
                        </div>
                        <div class="tweet-info-counts">

                            <div class="comments">
                                <button style="background: white; border: none;">
                                    <svg class="feather feather-message-circle sc-dnqmqq jxshSx"
                                         xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round" aria-hidden="true">
                                        <path
                                                d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z">
                                        </path>
                                    </svg>
                                </button>
                                <div class="comment-count"></div>
                            </div>

                            <div class="retweets">
                                <button style="background: white; border: none;">
                                    <svg class="feather feather-repeat sc-dnqmqq jxshSx"
                                         xmlns="http://www.w3.org/2000/svg"
                                         width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                         stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                         aria-hidden="true">
                                        <polyline points="17 1 21 5 17 9"></polyline>
                                        <path d="M3 11V9a4 4 0 0 1 4-4h14"></path>
                                        <polyline points="7 23 3 19 7 15"></polyline>
                                        <path d="M21 13v2a4 4 0 0 1-4 4H3"></path>
                                    </svg>
                                </button>
                                <div class="retweet-count"></div>
                            </div>

                            <div class="likes">
                                <button style="background: white; border: none;">
                                    <svg class="feather feather-heart sc-dnqmqq jxshSx"
                                         xmlns="http://www.w3.org/2000/svg"
                                         width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                         stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                         aria-hidden="true">
                                        <path
                                                d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z">
                                        </path>
                                    </svg>
                                </button>
                                <div class="likes-count"></div>
                            </div>

                            <!-- DELETE -->
                            {% if request.user.id == post.user.id %}
                                <div class="trash">
                                    <a href="{% url 'twitter:delete-post' pk=post.id %}"
                                       style="background: white; border: none;">
                                        <i class="fa fa-trash-o" style="color:#657786; font-size: 20px"
                                           aria-hidden="true"></i>
                                    </a>
                                </div>
                            {% endif %}
                            <!-- END-DELETE -->
                        </div>
                    </div>
                    <!-- FOR LOOP HERE -->

                </div>
            {% endfor %}
            <!-- EndTweets -->


        </div>
        <!-- End Center -->


        <!-- Barra Derecha -->
        <div class="sidebar m-5 d-none d-xl-block">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    Who to Follow
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><a href="#"
                                                   style="text-decoration: none;color: #657787;">@mundopython</a>
                    </li>
                    <li class="list-group-item"><a href="#"
                                                   style="text-decoration: none;color: #657787;">@mundopython</a>
                    </li>
                    <li class="list-group-item"><a href="#"
                                                   style="text-decoration: none;color: #657787;">@mundopython</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

{% endblock content %}